### ISSUE TITLE
Regarding the issue of reproducing experimental results

### ISSUE THREAD

**Issue by MH-limarco** [LiuChuang0059/Gradformer#1]
Hello:

Thanks for your open source code, this is an innovative and interesting paper. But I encountered some problems in the experiment when using your code. Mainly, in some cases, I can't achieve the performance described in the paper. So I'm checking here to see if I missed some details.

The following are the results of my experiments:

### NCI1
```
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 4, 0.0, 5, 0.6, 0, 0.5, 0.0, :::::::::, 0.80292, 0.80779
gnn, 10, 0.0, 5, 0.6, 0, 0.5, 0.0, :::::::::, 0.82968, 0.84672
```

### PROTEINS
```
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 10, 0.0, 5, 0.6, 0, 0.5, 0.0, :::::::::, 0.76577, 0.71429
```

### MUTAG
```
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 10, 0.0, 5, 0.7, 0, 0.5, 0.0, :::::::::, 0.94444, 0.75000
```

### COLLAB
```
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 10, 0.0, 5, 0.7, 0, 0.5, 0.0, :::::::::, 0.78200, 0.79200
```

### CLUSTER
``` python
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 16, 0.1, 0, 0.3, 0, 0.5, 0.0, :::::::::, 0.76698, 0.76795
```

**Comment by Celin-Yao** [comment]
Hello:
Thank you very much for your attention and interest in this article! Regarding the experiment you mentioned, we successfully reproduced it on a server equipped with an NVIDIA 4090 GPU. Here are the results:

**NCI1** : 
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 4, 0.1, 5, 0.6, 0, 0.5, 0.0, :::::::::, 0.81265,0.86131
**PROTEINS**:
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 4, 0, 5, 0.7, 0, 0.5, 0.0, :::::::::, 0.77477,0.77679
**MUTAG**:
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 12, 0, 5, 0.6, 0, 0.5, 0.0, :::::::::, 0.88889,0.85
**COLLAB**:
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 4, 0, 3, 0.7, 0, 0.5, 0.0, :::::::::, 0.812,0.828
**CLUSTER**:
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 16, 0, 0, 0.3, 0.1, 0.5, 0.0, :::::::::, 0.78371,0.78426

I hope this response addresses your concerns.

**Comment by MH-limarco** [comment]
Thanks for your repetition

I have successfully reproduced most of the experiments according to your settings,
but I still cannot reproduce the results of ZINC
Can you provide the .sh file of ZINC?

**NCI1:**
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 4, 0.1, 5, 0.6, 0, 0.5, 0.0, :::::::::, 0.83942, 0.86618

**PROTEINS:**
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 4, 0.0, 5, 0.7, 0, 0.5, 0.0, :::::::::, 0.76577, 0.72321

**MUTAG:**
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 12, 0.0, 5, 0.5, 0, 0.5, 0.0, :::::::::, 0.88889, 0.80000

**COLLAB:**
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 4, 0.0, 3, 0.7, 0, 0.5, 0.0, :::::::::, 0.81000, 0.80800

**CLUSTER:**
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 16, 0.0, 0, 0.3, 0.1, 0.5, 0, :::::::::, 0.77807, 0.77491

**ZINC:**
Method,Layer-Num,Slope,n_hop,gamma,drop_out,attn_drop,drop_path,::::::::,val,test
gnn, 10, 0.2, 5, 0.7, 0.0, 0.5, 0.0, :::::::::, 0.14364, 0.12600

**Comment by Celin-Yao** [comment]
Hello, we have added the ZINC dataset setting to our bash file, following the configuration of GraphGPS. You may now check it.
